# Generated by Django 2.2.4 on 2022-02-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0032_direcciones_subdireccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetivos',
            name='end_date',
            field=models.DateField(editable=False, null=True),
        ),
    ]
