# Generated by Django 2.2.4 on 2022-03-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0033_objetivos_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objetivos',
            options={'ordering': ['end_date']},
        ),
        migrations.AddField(
            model_name='objetivos',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
